### ISSUE TITLE
Bug - Results not being loaded/displayed

### ISSUE THREAD

**Issue by neosaybin88** [tiagonmas/azdo.ext.whatsup#6]
I followed ADO 211423, ADO 353202, and ADO 338507. 

My filter was set as “Show items updated since a week ago” and view is “all field change and comments”. 

All 3 ADO entries have comment updates this week but the feed is only displaying comment updates from ADO 353202.

**Comment by tiagonmas** [comment]
Confirmed as bug. Will investigate.

**Comment by tiagonmas** [comment]
@neosaybin88 found that the bug is due to the work items having more than 200 revisions and currently the extension is only fetching the first 200 updates. Need to implement pooling to fetch all updates above revision 200. Thanks for raising this issue :)

**Comment by tiagonmas** [comment]
@neosaybin88  Just deployed a fix. Please help testing. Thanks
