### ISSUE TITLE
Feature request - defining the query ID/item ID from the URL

### ISSUE THREAD

**Issue by luckylukash** [tiagonmas/azdo.ext.whatsup#9]
Adding the ability to define the query ID/item(s) ID from the URL would allow to easily follow multiple views by bookmarking different URLs.

**Comment by tiagonmas** [comment]
Thanks for the suggestion @luckylukash. Ease to implement. will update as soon as I get it published.

**Comment by tiagonmas** [comment]
@luckylukash you can now load items from a query id provided in the query string :)
just use queryid=<id of the query>

**Comment by luckylukash** [comment]
Awesome! Thanks a lot, @tiagonmas!
